### PR TITLE
13 new skin parts

### PR DESCRIPTION
**Pull request by ClockGen**
Skin preview in 3d-armor and skinsdb looks really weird (in both default and unified inventory, and probably others) - armor items are overlayed over the character_creator icon. This PR changes the texture to a "placeholder" texture with size of a skin preview.
Before:
Screenshot_20190814_000626
After:
Screenshot_20190814_001403

Also this PR adds 13 new skin parts.

### CODE REVIEW

**Comment by bell07** [comment]
The "inventory_plus_character_creator.png" texture is initially for Inventory buttons, (in inventories with buttons, like unified_inventory or inventory_plus) I used it as quick-and-dirty solution for preview. Please do not overwrite the file, but create a new one. Then adjust the line [258](https://github.com/minetest-mods/character_creator/blob/master/init.lua#L258)

By the way, in my "next generation" skins handling [player_api_modpack](https://github.com/bell07/minetest-player_api_modpack) the preview is generated (thx. to  GreenXenith). May you test his https://github.com/GreenXenith/skinsdb fork I copied the code from.
<details>
<summary>Screenshots</summary>

grafik

grafik
</details>

**Comment by ClockGen** [comment]
@bell07 hello, I added suggested changes.

**Comment by bell07** [comment]
if the #23 is merged you can remove the preview file ;-)

**Comment by bell07** [comment]
@ClockGen, please remove the preivew file, since skinsdb generates  (#23 is merged). Then I merge the new skin parts

**Comment by ClockGen** [comment]
@bell07 I've removed the other commit.

**Pull request merged**
